### ISSUE TITLE
I would like to learn API endpoint.

### ISSUE THREAD

**Issue by tekinarslan** [werpat/bahn-preisfinder#1]
Hello,

I am trying to find DB search endpoint in their marketplace but I can't. (https://developers.deutschebahn.com/db-api-marketplace/apis/)

Could you please share your project rest API address? 

Thank you

**Comment by werpat** [comment]
Actually its not using an offical API. I just reverse engineered the dataflow of the original search function on their website and used their internal endpoints. Thus these endpoints can change anytime and break corresponding projects. Also no public documentation (as far as I know) exists. (additional one should probably not send a load of requests to this endpoint).

This also results in the need of using a proxy (here nginx proxy-pass with added headers) for the requests to add matching cors-headers to the response so the responses are usable in a javascript project.

The internal API-Endpoints with corresponding request-objects I used are more or less found in [App.vue](https://github.com/werpat/bahn-preisfinder/blob/main/preisfinder-app/src/App.vue) and the proxy-config [nginx-default.conf](https://github.com/werpat/bahn-preisfinder/blob/main/nginx-default.conf) and are https://www.bahn.de/web/api/reiseloesung/orte and https://www.bahn.de/web/api/angebote/fahrplan
